"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.2.16.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
from pathlib import Path

import dj_database_url
from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# .env fayli bo'lsa o'qiymiz (ishlab chiqishda qulay, serverda esa odatda
# muhit o'zgaruvchilari to'g'ridan-to'g'ri beriladi).
load_dotenv(BASE_DIR / '.env')


def env_bool(name, default=False):
    """Muhit o'zgaruvchisini mantiqiy qiymatga o'giradi."""
    return os.getenv(name, str(default)).strip().lower() in ('1', 'true', 'yes', 'on')


def env_list(name, default=''):
    """Vergul bilan ajratilgan ro'yxatni o'qiydi."""
    return [item.strip() for item in os.getenv(name, default).split(',') if item.strip()]


# DEBUG standart bo'yicha o'chiq — serverda tasodifan yoqilib qolmasligi
# uchun. Ishlab chiqishda .env faylida DEBUG=True qilinadi.
DEBUG = env_bool('DEBUG', False)

# SECRET_KEY muhit o'zgaruvchisidan olinadi. DEBUG rejimida qiymat
# berilmagan bo'lsa vaqtinchalik kalit ishlatiladi; productionda esa
# yo'qligi darrov xato beradi — jimgina zaif kalit bilan ishlamasin.
SECRET_KEY = os.getenv('SECRET_KEY')
if not SECRET_KEY:
    if DEBUG:
        SECRET_KEY = 'django-insecure-faqat-ishlab-chiqish-uchun-kalit'
    else:
        raise RuntimeError(
            'SECRET_KEY muhit o\'zgaruvchisi berilmagan. '
            'Yangi kalit yaratish: python manage.py shell -c '
            '"from django.core.management.utils import get_random_secret_key; '
            'print(get_random_secret_key())"'
        )

ALLOWED_HOSTS = env_list('ALLOWED_HOSTS', 'localhost,127.0.0.1' if DEBUG else '')

# Formalar HTTPS orqali yuborilganda kerak (Django 4+ talabi).
CSRF_TRUSTED_ORIGINS = env_list('CSRF_TRUSTED_ORIGINS')


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'blog',

    # 3rd party
    'rest_framework',
    'rest_framework.authtoken',
    'django_filters',
]

REST_FRAMEWORK = {
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticatedOrReadOnly',
    ],
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework.authentication.TokenAuthentication',
        'rest_framework.authentication.SessionAuthentication',
    ],
    'DEFAULT_FILTER_BACKENDS': [
        'django_filters.rest_framework.DjangoFilterBackend',
        'rest_framework.filters.SearchFilter',
        'rest_framework.filters.OrderingFilter',
    ],
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 10,
    'DEFAULT_THROTTLE_CLASSES': [
        'rest_framework.throttling.AnonRateThrottle',
        'rest_framework.throttling.UserRateThrottle',
    ],
    'DEFAULT_THROTTLE_RATES': {
        'anon': '100/hour',      # anonim o'qish uchun umumiy chegara
        'user': '1000/hour',     # tizimga kirgan foydalanuvchi
        'comment': '10/hour',    # izoh yozish — spamga qarshi
        'login': '5/min',        # token olish — parol tanlashga qarshi
    },
}

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    # Statik fayllarni Django o'zi tarqatadi — alohida nginx sozlash shart emas
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'blog.context_processors.site_context',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

# DATABASE_URL berilgan bo'lsa o'sha ishlatiladi (masalan PostgreSQL:
# postgres://user:parol@host:5432/dbname), aks holda SQLite.
# .env da "DATABASE_URL=" bo'sh qoldirilishi mumkin — shuning uchun bo'sh
# satrni ham berilmagan deb hisoblaymiz.
DATABASES = {
    'default': dj_database_url.parse(
        os.getenv('DATABASE_URL') or f'sqlite:///{BASE_DIR / "db.sqlite3"}',
        conn_max_age=600,
        conn_health_checks=True,
    )
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'
# collectstatic shu papkaga yig'adi — serverda whitenoise shu yerdan tarqatadi
STATIC_ROOT = BASE_DIR / 'staticfiles'

# Manifest storage collectstatic yugurtirilishini talab qiladi, shuning uchun
# faqat productionda. Ishlab chiqishda va testlarda oddiy storage ishlatiladi.
_static_backend = (
    'django.contrib.staticfiles.storage.StaticFilesStorage'
    if DEBUG else
    # Fayl nomiga hash qo'shadi va siqadi — brauzer keshi to'g'ri ishlaydi
    'whitenoise.storage.CompressedManifestStaticFilesStorage'
)

STORAGES = {
    'default': {
        'BACKEND': 'django.core.files.storage.FileSystemStorage',
    },
    'staticfiles': {
        'BACKEND': _static_backend,
    },
}

# Media files (foydalanuvchi yuklagan rasmlar)
MEDIA_URL = 'media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Productionda media fayllarni whitenoise tarqatadi (config/urls.py ga qarang).
#
# Diqqat: ko'p hosting'larda disk vaqtinchalik — qayta joylashda yuklangan
# rasmlar yo'qoladi. Jiddiy loyihada S3 kabi tashqi saqlash yoki doimiy disk
# (Render Disk, Railway Volume) kerak bo'ladi.

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


# Xavfsizlik
# https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/
#
# Quyidagilar faqat productionda (DEBUG=False) yoqiladi — ishlab chiqishda
# HTTPS bo'lmagani uchun SSL talab qilish saytni ochib bo'lmaydigan qiladi.

if not DEBUG:
    # HTTPS ga yo'naltirish. Reverse-proxy (nginx, Render, Railway) o'zi
    # yo'naltirsa, .env da SECURE_SSL_REDIRECT=False qilish mumkin.
    SECURE_SSL_REDIRECT = env_bool('SECURE_SSL_REDIRECT', True)
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')

    # Cookie'lar faqat HTTPS orqali yuborilsin
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True

    # HSTS — brauzerga "bu saytga faqat HTTPS bilan kir" deydi.
    # Diqqat: bir marta yoqilgach brauzer buni uzoq eslab qoladi.
    # Shuning uchun boshida kichik qiymat (masalan 3600) bilan sinab ko'ring.
    SECURE_HSTS_SECONDS = int(os.getenv('SECURE_HSTS_SECONDS', '3600'))
    SECURE_HSTS_INCLUDE_SUBDOMAINS = env_bool('SECURE_HSTS_INCLUDE_SUBDOMAINS', False)
    SECURE_HSTS_PRELOAD = env_bool('SECURE_HSTS_PRELOAD', False)

    # Qo'shimcha himoya sarlavhalari
    SECURE_CONTENT_TYPE_NOSNIFF = True
    X_FRAME_OPTIONS = 'DENY'
    SESSION_COOKIE_HTTPONLY = True

    # Xatolarni konsolga yozamiz — server loglarida ko'rinadi
    LOGGING = {
        'version': 1,
        'disable_existing_loggers': False,
        'formatters': {
            'verbose': {
                'format': '{levelname} {asctime} {name} {message}',
                'style': '{',
            },
        },
        'handlers': {
            'console': {
                'class': 'logging.StreamHandler',
                'formatter': 'verbose',
            },
        },
        'root': {
            'handlers': ['console'],
            'level': os.getenv('LOG_LEVEL', 'INFO'),
        },
        'loggers': {
            'django.request': {
                'handlers': ['console'],
                'level': 'ERROR',
                'propagate': False,
            },
        },
    }
